service: fake-hgv-api

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: eu-west-1

functions:
  vehicle:
    handler: src/vehicle.main
    events:
     - http:
         path: vehicle/moth
         method: get
  testhistory:
    handler: src/testHistory.main
    events:
     - http:
         path: testhistory/moth
         method: get
